config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :students
  resources :groups
  resources :lessons
  resources :courses
  resources :tutors
  post 'lessons/attendance'
  post 'lessons/statistics_lesson'

   root 'groups#index'

end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  has_and_belongs_to_many :courses

def self.tutor_parse
  file = File.read("/home/fomy/rails/project/data/К04-361.json")

  data_hash = JSON.parse(file)

  data_hash['schedules'].each do |schedule|
    schedule['tutors'].each do |tutorJSON|
      tutor = Tutor.new
      tutor.last_name = tutorJSON['last_name']
      tutor.first_name = tutorJSON['first_name']
      tutor.second_name = tutorJSON['second_name']
        if !(Tutor.exists?(:last_name => tutor.last_name, :first_name => tutor.first_name, :second_name => tutor.second_name))
          tutor.save
        end
      end
    end
  end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    #Tutor.tutor_parse
    @tutors = Tutor.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:first_name, :second_name, :last_name)
    end
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/tutors/_form.html.erb
<%= form_for(@tutor) do |f| %>
  <% if @tutor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
      <% @tutor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_area :first_name %>
  </div>
  <div class="field">
    <%= f.label :second_name %><br>
    <%= f.text_area :second_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutors/edit.html.erb
<h1>Editing Tutor</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutor %> |
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tutors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Second name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  


    <% @tutors.each do |tutor| %>
      <tr>
        <td><%= tutor.first_name %></td>
        <td><%= tutor.second_name %></td>
        <td><%= tutor.last_name %></td>
        <td><%= link_to 'Show', tutor %></td>
        <td><%= link_to 'Edit', edit_tutor_path(tutor) %></td>
        <td><%= link_to 'Destroy', tutor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutor', new_tutor_path %>

app/views/tutors/new.html.erb
<h1>New Tutor</h1>

<%= render 'form' %>

<%= link_to 'Back', tutors_path %>

app/views/tutors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @tutor.first_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%= @tutor.second_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @tutor.last_name %>
</p>

<%= link_to 'Edit', edit_tutor_path(@tutor) %> |
<%= link_to 'Back', tutors_path %>