config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :students
  resources :groups
  resources :lessons
  resources :courses
  resources :tutors
  post 'lessons/attendance'
  post 'lessons/statistics_lesson'

   root 'groups#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :courses
  has_many :students, dependent: :destroy
  has_many :lessons, dependent: :destroy


  def self.group_parse

    file = File.read("/home/fomy/rails/project/data/К04-361.json")

    data_hash = JSON.parse(file)

    data_hash['schedules'].each do |schedule|
    schedule['courses'].each do |groupJSON|
        group = Group.new
        group.name = groupJSON['group']['name']
        if (Group.find_by name: group.name)==nil
          group.save
        end
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    #  Group.group_parse
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @groups = Group.all

  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='text-center'>Весенний семестр 2015/2016 учебного года</h2>
  <ul class="nav nav-tabs">
    <li class="active"><a href="#a" data-toggle="tab">А</a></li>
    <li><a href="#kib" data-toggle="tab">КиБ</a></li>
    <li><a href="#t" data-toggle="tab">Т</a></li>
    <li><a href="#u" data-toggle="tab">У</a></li>
    <li><a href="#f" data-toggle="tab">Ф</a></li>
  </ul>


  <div class="tab-content">
    <div class="tab-pane active" id="a">A</div>
    <div class="tab-pane" id="kib">
      <h2 class="light">Факультет кибернетики и информационной безопасности</h2>
      <div class="row">
        <div class="col-sm-2">
          <h4>1 курс</h4>
            <div class="list-group">
            <% @groups.order(:name).each do |group| %>
            <% if (group.year == 1)&&(group.faculty == "kib") %>
            <%= link_to group.name, group, class: "list-group-item" %>
            <% end %>
            <% end %>
            </div>
        </div>
        <div class="col-sm-2">
          <h4>2 курс</h4>
            <div class="list-group">
            <% @groups.order(:name).each do |group| %>
            <% if (group.year == 2)&&(group.faculty == "kib") %>
            <%= link_to group.name, group, class: "list-group-item" %>
            <% end %>
            <% end %>
            </div>
        </div>
        <div class="col-sm-2">
          <h4>3 курс</h4>
            <div class="list-group">
            <% @groups.order(:name).each do |group| %>
            <% if (group.year == 3)&&(group.faculty == "kib") %>
            <%= link_to group.name, group, class: "list-group-item" %>
            <% end %>
            <% end %>
            </div>
        </div>
        <div class="col-sm-2">
          <h4>4 курс</h4>
            <div class="list-group">
            <% @groups.order(:name).each do |group| %>
            <% if (group.year == 4)&&(group.faculty == "kib") %>
            <%= link_to group.name, group, class: "list-group-item" %>
            <% end %>
            <% end %>
            </div>
        </div>
        <div class="col-sm-2">
          <h4>5 курс</h4>
            <div class="list-group">
            <% @groups.order(:name).each do |group| %>
            <% if (group.year == 5)&&(group.faculty == "kib") %>
            <%= link_to group.name, group, class: "list-group-item" %>
            <% end %>
            <% end %>
            </div>
        </div>

      </div>

    </div>




    <div class="tab-pane" id="t">t</div>
    <div class="tab-pane" id="u">u</div>
    <div class="tab-pane" id="f">f</div>

  </div>
 </div>
    <!-- <% @groups.each do |group| %> -->
    <!-- <ul class="list-group-item"> -->
    <!-- <%= link_to group.name, group %> -->

<!-- </ul> -->

      <!-- <tr> -->
        <!-- <td><%= group.name %></td> -->
        <!-- <td><%= link_to 'Show', group %></td> -->
        <!-- <td><%= link_to 'Edit', edit_group_path(group) %></td> -->
        <!-- <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      <!-- </tr> -->
    <!-- <% end %> -->
  <!-- </tbody> -->
<!-- </table> -->


<!-- <%= link_to 'New Group', new_group_path %> -->

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class='text-center'>

  <%= @group.name %>
</br>
  <strong>Расписание  </strong>
  <%courses= @group.courses %>

</h2>


<div class="table-responsive">
<table class="table table-condensed table-hover table-striped">
  <thead>
    <tr>
      <th>Время</th>
      <th>Название дисциплины</th>
      <th>Тип</th>
      <th>Аудитория</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
    <%flag = false%>
    <% courses.each do |course| %>
       <% if course.wday == 1 %>
       <% flag = true%>
      <% end %>
      <% end %>
      <% if flag == true %>
  <tr>
    <td colspan="4" >
      <b>Понедельник</b>
    </td>
  </tr>
    <% courses.order(:started_time).each do |course| %>
<% if course.wday == 1  %>

    <tr>
    <%if ((course.finished_time%60)>9)%>
    <td><%= (course.started_time / 60).to_s + ":" +  (course.started_time % 60).to_s + "-" + (course.finished_time / 60).to_s + ":" + (course.finished_time % 60).to_s %></td>
    <%else%>
    <td><%= (course.started_time / 60).to_s + ":"  + (course.started_time % 60).to_s  + "-" + (course.finished_time / 60).to_s + ":" + "0" + (course.finished_time % 60).to_s %></td>
    <% end %>
      <td> <%= link_to course.name, lessons_path(course: course.id, group: @group.id) %></td>
      <td><%= course.human_htype %>
         <%if course.period == 1%>
          <%="(нечёт)" %>
          <% elsif course.period == 2 %>
          <%="(чёт)"%>
          <%end%></td>
      <td><%= course.room_name %></td>
    </tr>
    <% end %>
    <% end %>
    <% end %>
    <%flag = false%>
    <% courses.each do |course| %>
       <% if course.wday == 2 %>
       <% flag = true%>
      <% end %>
    <% end %>

      <% if flag == true %>

    <tr>
      <td colspan="4", align="center">
        <b>Вторник</b>
      </td>
    </tr>
      <% courses.order(:started_time).each do |course| %>
  <% if course.wday == 2  %>

      <tr>

        <%if ((course.finished_time%60)>9)%>
          <td><%= (course.started_time / 60).to_s + ":" +  (course.started_time % 60).to_s + "-" + (course.finished_time / 60).to_s + ":" + (course.finished_time % 60).to_s %></td>
          <%else%>
          <td><%= (course.started_time / 60).to_s + ":"  + (course.started_time % 60).to_s  + "-" + (course.finished_time / 60).to_s + ":" + "0" + (course.finished_time % 60).to_s %></td>
        <% end %>
        <td> <%= link_to course.name, lessons_path(course: course.id, group: @group.id) %>

      </td>
        <td><%= course.human_htype %>
          <%if course.period == 1%>
            <%="(нечёт)" %>
            <% elsif course.period==2 %>
            <%="(чёт)"%>
            <%end%></td>
        <td><%= course.room_name %></td>
      </tr>
      <% end %>
      <% end %>
      <% end %>

      <%flag = false%>
      <% courses.each do |course| %>
         <% if course.wday == 3 %>
         <% flag = true%>
        <% end %>
      <% end %>

        <% if flag == true %>

      <tr>
        <td colspan="4", align="center">
        <b>Среда</b>
        </td>
      </tr>
        <% courses.order(:started_time).each do |course| %>
    <% if course.wday ==3  %>


        <tr>

          <%if ((course.finished_time%60)>9)%>
            <td><%= (course.started_time / 60).to_s + ":" +  (course.started_time % 60).to_s + "-" + (course.finished_time / 60).to_s + ":" + (course.finished_time % 60).to_s %></td>
            <%else%>
            <td><%= (course.started_time / 60).to_s + ":"  + (course.started_time % 60).to_s  + "-" + (course.finished_time / 60).to_s + ":" + "0" + (course.finished_time % 60).to_s %></td>
          <% end %>
          <span title="" data-toggle="tooltip" class="lesson-square lesson-square-1" style="font-family: Ubuntu" data-original-title="Нечетная неделя"></span>
          <td> <%= link_to course.name, lessons_path(course: course.id, group: @group.id) %></td>
          <td><%= course.human_htype %>
            <%if course.period == 1%>
              <%="(нечёт)" %>
              <% elsif course.period==2 %>
              <%="(чёт)"%>
              <%end%></td>
          <td><%= course.room_name %></td>
        </tr>
        <% end %>
        <% end %>
        <% end %>

        <%flag = false%>
        <% courses.each do |course| %>
           <% if course.wday == 4 %>
           <% flag = true%>
          <% end %>
        <% end %>

          <% if flag == true %>

        <tr>
          <td colspan="4", align="center">
          <b>Четверг</b>
          </td>
        </tr>
          <% courses.order(:started_time).each do |course| %>
      <% if course.wday == 4  %>

          <tr>

            <%if ((course.finished_time%60)>9)%>
              <td><%= (course.started_time / 60).to_s + ":" +  (course.started_time % 60).to_s + "-" + (course.finished_time / 60).to_s + ":" + (course.finished_time % 60).to_s %></td>
              <%else%>
              <td><%= (course.started_time / 60).to_s + ":"  + (course.started_time % 60).to_s  + "-" + (course.finished_time / 60).to_s + ":" + "0" + (course.finished_time % 60).to_s %></td>
            <% end %>
            <td> <%= link_to course.name, lessons_path(course: course.id, group: @group.id) %></td>
            <td><%= course.human_htype %>  <%if course.period == 1%>
                <%="(нечёт)" %>
                <% elsif course.period==2 %>
                <%="(чёт)"%>
                <%end%></td>
            <td><%= course.room_name %></td>
          </tr>
          <% end %>
          <% end %>
          <% end %>

          <%flag = false%>
          <% courses.each do |course| %>
             <% if course.wday == 5 %>
             <% flag = true%>
            <% end %>
          <% end %>

            <% if flag == true %>

          <tr>
            <td colspan="4", align="center">
              <b>Пятница</b>
            </td>
          </tr>
            <% courses.order(:started_time).each do |course| %>
        <% if course.wday == 5  %>

            <tr>

              <%if ((course.finished_time%60)>9)%>
                <td><%= (course.started_time / 60).to_s + ":" +  (course.started_time % 60).to_s + "-" + (course.finished_time / 60).to_s + ":" + (course.finished_time % 60).to_s %></td>
                <%else%>
                <td><%= (course.started_time / 60).to_s + ":"  + (course.started_time % 60).to_s  + "-" + (course.finished_time / 60).to_s + ":" + "0" + (course.finished_time % 60).to_s %></td>
              <% end %>
              <td> <%= link_to course.name, lessons_path(course: course.id, group: @group.id) %></td>
              <td><%= course.human_htype %>  <%if course.period == 1%>
                  <%="(нечёт)" %>
                  <% elsif course.period==2 %>
                  <%="(чёт)"%>
                  <%end%></td>
              <td><%= course.room_name %></td>
            </tr>
            <% end %>
            <% end %>
            <% end %>


            <%flag = false%>
            <% courses.each do |course| %>
               <% if course.wday == 6 %>
               <% flag = true%>
              <% end %>
            <% end %>

              <% if flag == true %>

            <tr>
              <td colspan="4", align="center">
              <b>Суббота</b>
              </td>
            </tr>
              <% courses.order(:started_time).each do |course| %>
          <% if course.wday == 6  %>

              <tr>

                <%if ((course.finished_time%60)>9)%>
                  <td><%= (course.started_time / 60).to_s + ":" +  (course.started_time % 60).to_s + "-" + (course.finished_time / 60).to_s + ":" + (course.finished_time % 60).to_s %></td>
                  <%else%>
                  <td><%= (course.started_time / 60).to_s + ":"  + (course.started_time % 60).to_s  + "-" + (course.finished_time / 60).to_s + ":" + "0" + (course.finished_time % 60).to_s %></td>
                <% end %>
                <td> <%= link_to course.name, lessons_path(course: course.id, group: @group.id) %></td>
                <td><%= course.human_htype %>  <%if course.period == 1%>
                    <%="(нечёт)" %>
                    <% elsif course.period==2 %>
                    <%="(чёт)"%>
                    <%end%></td>
                <td><%= course.room_name %></td>
              </tr>
              <% end %>
              <% end %>
              <% end %>
  </tbody>
</table>
</div>
<br>